name: Build MW4530R USB OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init feed and config
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          cat > .config <<EOF
          CONFIG_TARGET_ath79=y
          CONFIG_TARGET_ath79_generic=y
          CONFIG_TARGET_ath79_generic_DEVICE_mercury_mw4530r-v1=y
          CONFIG_TARGET_ROOTFS_SQUASHFS=y
          
          # 基础 USB 驱动
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-uhci=y
          CONFIG_PACKAGE_kmod-usb-ledtrig-usbport=y
          
          # USB 网络支持
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb-net-asix=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y
          
          # 手机 USB 共享（Tethering）
          CONFIG_PACKAGE_usb-modeswitch=y
          CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y
          CONFIG_PACKAGE_kmod-usb-serial-option=y
          
          # PPP 支持（拨号上网）
          CONFIG_PACKAGE_ppp=y
          CONFIG_PACKAGE_ppp-mod-pppoe=y
          CONFIG_PACKAGE_kmod-pppoe=y
          CONFIG_PACKAGE_kmod-pppox=y
          
          # 其他推荐工具（可选）
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-proto-ppp=y
          CONFIG_PACKAGE_luci-proto-ncm=y
          
          EOF

          make defconfig

      - name: Cache downloads
        uses: actions/cache@v4
        with:
          path: |
            dl
            build_dir
          key: openwrt-${{ github.run_id }}

      - name: Build firmware
        run: make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: MW4530R-USB-Firmware
          path: bin/targets/ath79/generic/*.bin
