name: Build MW4530R USB OpenWrtmain

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
      
      - name: Update feeds and install
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Create default config with USB, wired and wireless drivers
        run: |
          cat > .config <<EOF
          CONFIG_TARGET_ath79=y
          CONFIG_TARGET_ath79_generic=y
          CONFIG_TARGET_ath79_generic_DEVICE_mercury_mw4530r-v1=y

          CONFIG_TARGET_ROOTFS_SQUASHFS=y

          # LuCI 和中文
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y

          # USB 相关驱动
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-uhci=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-ipheth=y
          CONFIG_PACKAGE_kmod-usb-serial=y
          CONFIG_PACKAGE_kmod-usb-serial-option=y
          CONFIG_PACKAGE_kmod-usb-serial-wwan=y
          CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y

          CONFIG_PACKAGE_usbutils=y
          CONFIG_PACKAGE_umbim=y
          CONFIG_PACKAGE_wwan=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_kmod-nls-base=y

          CONFIG_PACKAGE_luci-proto-ppp=y
          CONFIG_PACKAGE_luci-proto-qmi=y
          CONFIG_PACKAGE_luci-proto-ncm=y
          CONFIG_PACKAGE_ppp=y
          CONFIG_PACKAGE_ppp-mod-pppoe=y

          # 有线和交换芯片驱动
          CONFIG_PACKAGE_kmod-swconfig=y
          CONFIG_PACKAGE_kmod-gpio-button-hotplug=y
          CONFIG_PACKAGE_kmod-mac80211=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_kmod-eth=y
          CONFIG_PACKAGE_swconfig=y

          EOF

          make defconfig

      - name: Cache downloads
        uses: actions/cache@v4
        with:
          path: dl
          key: openwrt-${{ github.run_id }}

      - name: Build firmware
        run: make -j$(nproc)

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: MW4530R-USB-Firmware-main
          path: bin/targets/ath79/generic/*.bin
